### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by jnptechnical** [maxkostinevich/woo-email-generator#1]
Fantastic plugin!

It'd be great to see:

Option to remove all the mailchimp pieces - header, footer, title etc (just so it only creates the HTML for the body - ready to be pasted into an existing template).

Option to customise the buttons/sale flashes (buttons/badges if possible)

Option to show normal and sale prices

Ability to customize background colour without editing the HTML - or all colours if possible - that'd be even better!

**Comment by maxkostinevich** [comment]
Hey @jnptechnical thanks for your suggestions, I have added it to my roadmap. I think that it will be ready somewhere at the end of January 2016.

**Comment by maxkostinevich** [comment]
@jnptechnical just let you know that I've decided to add full integration with mailchimp, with ability to manage email templates, campaigns and subscribers and send campaigns through WP-Admin Dashboard.

**Comment by jnptechnical** [comment]
Fantastic!

 

Regards,

Jack Wilson

For and on Behalf of
JNP Technical Solutions

07722318526
 <http://www.jnptechnical.co.uk> www.jnptechnical.co.uk

**Comment by BurlesonBrad** [comment]
@maxkostinevich Where's the 'Like' button? 
*oh wait, wrong platform* 
:+1: :+1: :+1: <----tada!

**Comment by maxkostinevich** [comment]
Hi there, sorry for late response, I've been busy with some client work. After some research I've decided to turn it into fully-featured Email Builder for WordPress, you can read more about this and subscribe to updates - https://maxkostinevich.com/blog/wordpress-email-builder/

**Comment by BurlesonBrad** [comment]
...dang client work 
Those high dollar clients keep me from being productive all the time :stuck_out_tongue_winking_eye:
